name: nogironlar_ilovasi
description: "A project for invalid people."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  speech_to_text: ^6.6.1
  flutter_dotenv: ^5.1.0
  url_launcher: ^6.2.5
  provider: ^6.1.2
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
  http: ^1.2.1
  just_audio: ^0.9.37
  google_ml_kit: ^0.16.3
  image_picker: ^1.1.0
  google_maps_flutter: ^2.2.8
  geolocator: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - .env
